export const CATEGORIES = [
  { id: 'all', label: 'Todas' },
  { id: 'musica', label: '🎵 Música' },
  { id: 'cultural', label: '🎭 Cultural' },
  { id: 'deportivo', label: '⚽ Deportivo' },
  { id: 'gastronomico', label: '🍽️ Gastronómico' },
  { id: 'academico', label: '🎓 Académico' },
  { id: 'entretenimiento', label: '🎉 Entretenimiento' },
];

export const FEATURED_EVENTS = [
  {
    id: 'festival-cartagena-jazz',
    category: 'Música',
    title: 'Festival Cartagena Jazz',
    date: 'Vie 22 ago · 7:00 PM',
    startsAt: '2026-08-22T19:00:00-05:00',
    location: 'Plaza de la Aduana, Centro Histórico',
    price: 85000,
    gradient: 'from-brand to-sky-300',
  },
  {
    id: 'noche-de-sabores',
    category: 'Gastronómico',
    title: 'Noche de Sabores de Getsemaní',
    date: 'Sáb 23 ago · 6:30 PM',
    startsAt: '2026-08-23T18:30:00-05:00',
    location: 'Calle del Guerrero, Getsemaní',
    price: 60000,
    gradient: 'from-orange-400 to-accent',
  },
  {
    id: 'clase-de-ritmo',
    category: 'Entretenimiento',
    title: 'Clase de Ritmo al Atardecer',
    date: 'Dom 24 ago · 5:00 PM',
    startsAt: '2026-08-24T17:00:00-05:00',
    location: 'Plaza de los Coches',
    price: 30000,
    gradient: 'from-pink-500 to-violet-400',
  },
];

export const UPCOMING_EVENTS = [
  {
    id: 'feria-libro',
    category: 'Cultural',
    title: 'Feria del Libro de Cartagena',
    date: '12 – 20 sep',
    startsAt: '2026-09-12T10:00:00-05:00',
    location: 'Centro de Convenciones',
    price: 0,
    gradient: 'from-violet-500 to-sky-400',
    favorite: true,
  },
  {
    id: 'voley-bocagrande',
    category: 'Deportivo',
    title: 'Torneo de Vóley Playa · Bocagrande',
    date: 'Dom 7 sep · 9:00 AM',
    startsAt: '2026-09-07T09:00:00-05:00',
    location: 'Playa de Bocagrande',
    price: 25000,
    gradient: 'from-emerald-500 to-green-300',
    favorite: false,
  },
  {
    id: 'cine-baluarte',
    category: 'Entretenimiento',
    title: 'Cine bajo las estrellas · Baluarte',
    date: 'Jue 4 sep · 7:30 PM',
    startsAt: '2026-09-04T19:30:00-05:00',
    location: 'Baluarte de Sn. Francisco',
    price: 18000,
    gradient: 'from-pink-500 to-orange-300',
    favorite: false,
  },
  {
    id: 'catedra-historia',
    category: 'Académico',
    title: 'Cátedra de Historia Colonial',
    date: 'Mar 9 sep · 5:00 PM',
    startsAt: '2026-09-09T17:00:00-05:00',
    location: 'Universidad de Cartagena',
    price: 0,
    gradient: 'from-brand to-sky-300',
    favorite: false,
  },
  {
    id: 'festival-aretes',
    category: 'Música',
    title: 'Festival de Artes y Sonidos',
    date: 'Mié 17 sep · 8:00 PM',
    startsAt: '2026-09-17T20:00:00-05:00',
    location: 'Parque de la Marina',
    price: 45000,
    gradient: 'from-brand to-violet-400',
    favorite: false,
  },
  {
    id: 'mercado-gastronomico',
    category: 'Gastronómico',
    title: 'Mercado Gastronómico de la Bahía',
    date: 'Vie 19 sep · 6:00 PM',
    startsAt: '2026-09-19T18:00:00-05:00',
    location: 'Manga',
    price: 20000,
    gradient: 'from-orange-500 to-amber-300',
    favorite: true,
  },
];

export const POPULAR_PLACES = [
  { id: 'centro-historico', name: 'Centro Histórico', activeEvents: 128, gradient: 'from-brand-dark to-sky-300', lat: 10.3933, lng: -75.4851 },
  { id: 'getsemani', name: 'Getsemaní', activeEvents: 76, gradient: 'from-violet-500 to-sky-400', lat: 10.3912, lng: -75.4862 },
  { id: 'bocagrande', name: 'Bocagrande', activeEvents: 54, gradient: 'from-orange-400 to-accent', lat: 10.3954, lng: -75.5599 },
  { id: 'manglares', name: 'Manga', activeEvents: 41, gradient: 'from-emerald-500 to-sky-300', lat: 10.3885, lng: -75.5310 },
];
